// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelActivity } from "./ChannelActivity";
import type { GlobalActivity } from "./GlobalActivity";
import type { UserActivity } from "./UserActivity";

export type Activity = { type: "User", data: { activity: UserActivity, } } | { type: "Channel", data: { activity: ChannelActivity, } } | { type: "Global", data: { activity: GlobalActivity, } };