// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthPublic = { is: "Valid", data: { name: string, } } | { is: "Invalid", data: { reason: string, } };