// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RolePermissions } from "./RolePermissions";

export interface ChangeRoleBody { name: string, extends: Array<string>, editors: Array<string>, permissions: RolePermissions, }