// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelType } from "./ChannelType";

export interface CreateChannelBody { type: ChannelType, description: string, title: string, default_role: string, labels: Array<string>, }