// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveMessage = { is: "BlockConnected", data: { id: string, } } | { is: "BlockDisconnected", data: { id: string, } } | { is: "LabelsChanged" } | { is: "DescriptionChanged" } | { is: "BlockPinned", data: { id: string | null, } } | { is: "BlockChanged", data: { id: string, } };