// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneralError } from "./GeneralError";
import type { RoleError } from "./RoleError";

export type RoleWrappedError = { is: "Role", data: RoleError } | { is: "General", data: GeneralError };