// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RolePermissions } from "./RolePermissions";

export interface Role { id: string, owner: string, editors: Array<string>, name: string, extends: Array<string>, permissions: RolePermissions, }